### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by 0x010C** [whym/whois-gateway#11]
Hi,

I'm working on a JS gadget for Check Users, and I want to integrate some whois-data into it. But currently, I can't request the api because of a "Cross-Origin Request" issue.
Could you enable CORS for the wikimedia sites? Some doc here: http://tamercelik.com/212/how-to-enable-cors-in-lighttpd/

Thanks!

**Comment by whym** [comment]
I tried that, and then https://wikitech.wikimedia.org/wiki/Help:Toolforge/Web/Lighttpd but neither seemed to work from domains such as en.wikipedia.org. Interestingly, it works on meta.wikimedia.org. for me.

But maybe it fails because I'm trying from Scratchpad of Firefox? I'll leave in the Access-Control lines according to the Toolforge docs, for you to test.

**Comment by Huji** [comment]
What is the status of this? I am also contributing to [a gadget for CUs](https://github.com/Ladsgroup/CheckUserHelper) and this is needed for that gadget to work.

**Comment by Huji** [comment]
I think you can fix this by adding the following to the bottom of your `lighttpd.conf` file:

```
server.modules += (
    "mod_setenv",
)
setenv.add-response-header = ( "Access-Control-Allow-Origin" => "*" )
```

**Comment by 0x010C** [comment]
It seems that it has be done for fa.wikipedia.org, could it also be done for other wikimedia domains (especially fr.wikipedia.org)?

**Comment by Huji** [comment]
0x010C don't be confused. The one that I set up for temporary use at fawiki (located at `whois.wmflabs.org`) is not the same as the permanent instantiation of this tool located at `whois.toolforge.org`, formerly at `tools.wmflabs.org/whois`.
I'm happy to open up my temporary one to `*`, but I think either whym should fix his/hers, or we should retire his/hers and use the new one instead.

**Comment by whym** [comment]
Thank you for the suggestion.

> setenv.add-response-header = ( "Access-Control-Allow-Origin" => "*" )

I tried this. Is it working?

**Comment by 0x010C** [comment]
It works like a charm, thanks a lot!
