### ISSUE TITLE
Security vulnerability: T199260

### ISSUE THREAD

**Issue by urbanecm** [whym/whois-gateway#12]
Hello ,

please pay attention to https://phabricator.wikimedia.org/T199260. This task is non-public, as it describes security vulnerability which is not fixed, however, you should be able to view it. If not, please contact me.

Martin Urbanec

**Comment by whym** [comment]
Thank you for reminding me. I think I have fixed it, but if there is something I'm missing, please let me know. (The online tool has been updated, but the new version of the source code is kept there and not on GitHub yet.)

**Comment by urbanecm** [comment]
Yes, it works for me. Thanks!
