### ISSUE TITLE
Recent changes

### ISSUE THREAD

**Issue by DDGo** [whym/whois-gateway#5]
Hi,

I have seen there have been some changes to this tool, which are not really an improvement in my opinion.

For example at https://tools.wmflabs.org/whois/gateway.py?lookup=true&ip=213.124.37.58 there is a whole another added block of extra info of RIPE, which serves not so much purpose if I'm honest.

Also I see info like ip_version and more, which also doesn't give info you would really need. I also seem to miss the option of network CIDR (example: 213.124.37.56/29 for 213.124.37.56-63) and the description about the network itself, which was there untill recently.

I hope I'm not being too negative right now, but I hope you could take a look at this.

-- Wiki13 from Wikimedia

**Comment by whym** [comment]
@DDGo: I see what you mean. I partly changed it back and it should look closer to what it was.

**Comment by DDGo** [comment]
It looks way better now! The unneccasary clutter seems to gone. Thank you very much @whym !
