### ISSUE TITLE
Show extra info

### ISSUE THREAD

**Issue by DDGo** [whym/whois-gateway#8]
Hello,

I have a request, but I don't know if implementation is possible. This whois site [https://whois.domaintools.com/80.113.10.115](here) (example) shows some extra infromation about "person" "adress" and "email" (its near the bottom). Is it possible to also show this info in the whois tool? Or is there a reason to not show this info (eg. privacy)?

**Comment by whym** [comment]
Here are quick comments.

* Apparently no quick way to implement - I quickly skimmed the docs of the library I'm using ("ipwhois"), and I couldn't find how I extract the "person" field.
* Apparently less frequently used (?) - when would you need these bits of information?

**Comment by DDGo** [comment]
Hello.

On the Dutch Wikipedia I deal a lot with identifying schools. Some of the ISP's only give the information about the school itself in the second "address" section. The tool currently doesn't show this and it would be nice if it would show it.

If it's not possible or not yet supported in the python library I would be fine with closing this issue

**Comment by whym** [comment]
For future reference (in case I or someone else want to work on this) - the "person" and "role" appear to be part of [RPSL](https://tools.ietf.org/html/rfc2622).
